### ISSUE TITLE
no package

### ISSUE THREAD

**Issue by endlessydev** [biobootloader/wolverine#52]
**idunno if am stupid but this is my issus**

### Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/root/wolverine/wolverine/wolverine.py", line 8, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

**Comment by nervousapps** [comment]
Have you installed requirements ?

**Comment by matebenyovszky** [comment]
Still accurate: there is no published Wolverine package on PyPI, and no commit in this repository since March 2024.

For anyone landing on this issue looking for an installable version, we maintain a continuation: `pip install healing-agent` (Python 3.10–3.13, MIT, https://github.com/matebenyovszky/healing-agent).

It makes a different trade-off worth knowing about before you switch: it works as a decorator (`@healing_agent` on the function you want supervised) rather than as a CLI wrapper around a script. That is what gets live argument and local-variable values into the prompt instead of just the traceback — but it does mean touching the source. A Wolverine-style `run script.py` mode, for code you cannot import or decorate, is on the roadmap.
